### PR TITLE
Fix missing test coverage in tags

### PR DESCRIPTION
**Pull request by cfournie**
This increases the line test coverage to 100% for the tags module.

review/ @kmtaylor-github @honkfestival

### CODE REVIEW

**Comment by kmtaylor-github** [comment]
```
# pylint: disable=abstract-method
class MyTag(XMLSerializable):
   ...
E       TypeError: Can't instantiate abstract class MyTag with abstract methods _xml
```

Sigh...

**Comment by cfournie** [comment]
Bah. Well I'll just call it another (erroneous) way then.

**Comment by honkfestival** [comment]
Jumping through hoops like this just for 100% coverage doesn't add much value. Is it possible to disable code coverage for these bits instead?

**Comment by cfournie** [comment]
> Jumping through hoops like this just for 100% coverage doesn't add much value

True, but these aren't really hoops, they're legitimate tests of API functionality. I want to warn users loudly if they do something that's currently unsupported and I didn't test env vars or capture output at all.

**Comment by honkfestival** [comment]
> they're legitimate tests of API functionality

Gotcha. From the PR description, I thought you were just chasing the 100. :)

**Pull request merged**
