### PR TITLE
Release 0.0.6

### PR DESCRIPTION
**Pull request by sebmartin**
Change log
- Surface the client URL used to obtain a model (#78)
- Remove WorkflowBuilder in favour of WorkflowApp (#80)

### CODE REVIEW

**Comment by sebmartin** [comment]
https://github.com/Shopify/pyoozie/pull/52 was just merged, but not into `master`.  We'll need to merge [`workflow_decision`](https://github.com/Shopify/pyoozie/tree/workflow_decision) branch if we want to include that into this release.

**Comment by cfournie** [comment]
#52 recreated as https://github.com/Shopify/pyoozie/pull/80

**Comment by cfournie** [comment]
Merged #80, can you rebase to pick that up?

**Comment by sebmartin** [comment]
> Merged #80, can you rebase to pick that up?

Done. 👍 ?

**Pull request merged**
